openapi: 3.0.1
info:
  title: Example API
  version: 1.0.0
  description: Example OpenAPI definition for AWS CDK

paths:
  /hello:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: your-api-id
      region:
        default: us-east-1
      stage:
        default: prod
