name: Todoy-Tasks-dev-latest

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-3
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_ACCESS_SECRET:  ${{ secrets.AWS_ACCESS_SECRET }}
  ENV: dev
  STAGE: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_ACCESS_SECRET }}
          aws-region: ${{env.AWS_REGION}} 
      
      - name: Install packages
        working-directory: ./
        run: 'npm ci && cd ./Todoy-Server && npm ci'

      - name: Deploy CDK stack
        working-directory: ./Todoy-Server/cdk
        run: 'npx cdk deploy Todoy-Tasks-Stack-dev --require-approval never'
        env: 
          AWS_REGION: ${{env.AWS_REGION}}
          AWS_ACCESS_KEY: ${{ env.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET:  ${{ env.AWS_ACCESS_SECRET }}